USE [master]
GO
/****** Object:  Database [DmsAppDb]    Script Date: 7/6/2018 9:23:15 PM ******/
CREATE DATABASE [DmsAppDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DmsAppDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLSERVER\MSSQL\DATA\DmsAppDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DmsAppDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLSERVER\MSSQL\DATA\DmsAppDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DmsAppDb] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DmsAppDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DmsAppDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DmsAppDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DmsAppDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DmsAppDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DmsAppDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [DmsAppDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DmsAppDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DmsAppDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DmsAppDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DmsAppDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DmsAppDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DmsAppDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DmsAppDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DmsAppDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DmsAppDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DmsAppDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DmsAppDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DmsAppDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DmsAppDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DmsAppDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DmsAppDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DmsAppDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DmsAppDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DmsAppDb] SET  MULTI_USER 
GO
ALTER DATABASE [DmsAppDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DmsAppDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DmsAppDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DmsAppDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DmsAppDb] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DmsAppDb]
GO
/****** Object:  Table [dbo].[EmployeeInfo]    Script Date: 7/6/2018 9:23:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeInfo](
	[EmpId] [bigint] NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Dob] [datetime] NULL,
	[PrimaryEmail] [nvarchar](50) NULL,
	[SecondaryEmail] [nvarchar](50) NULL,
	[Gender] [nchar](10) NULL,
	[AddedByUser] [bigint] NULL,
	[AddedOn] [datetime] NULL,
	[UpdatedByUser] [bigint] NULL,
	[UpdatedOn] [datetime] NULL
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [DmsAppDb] SET  READ_WRITE 
GO
